#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

NAME="clipbridge-server"
PROG="/usr/bin/clipbridge-server"
CONFIG="/etc/clipbridge/config.yaml"
WORKDIR="/var/lib/clipbridge"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -config "$CONFIG"
	procd_set_param cwd "$WORKDIR"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "clipbridge"
}
